dist: trusty
sudo: false
git:
  depth: false
env:
  global:
    - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure: "DeWcLd39DyZs3QmRwKnbcZE1n8CkyTdGDOdEmwu0ywAxGJpGju+H+cXTIDiDUfYe0+lpezSpoVoCz3l9gjlPHdCLnn9Pj2l6sgM0oN+wDkFa9gJRpXU+IZxDOcczWpvTRSYLCSoAsCCBN82SjeEhU/pIAoM4hJwLg+FjUj2J9KP8sUpNsUpG97MefYQHlrqIRAMlZ7CwDUOmZv2iqTWs2hslDAArPX1XMaKEdPv4Zp17esfmkjOrgLkj96b45cuyJIXN2gr8KuFGLkqV7ZVofrIbEqL1l6cj1tOUCxfiStcq8qu2PE9gJbqZm51mJYA+FXTe6EZlgmGJdTZgH+cJyaABd381dFHMdRD55SUEpq7UeqqzpPleqrqb56kJ2So9pnko5plODhutjhaTB8Ov7vz6DVTFJ4fL9FzjYMX2MHbMrk+/Zh9S+7Cb/feiVPXWOh8fu3YqVlJzfttpshshj8xp9B6TZOpPkQoAaNewCRTm6uqQQuFjtAheymb01e9aMAfXVHIVm39RgZEnaUQBrSALhAqfDdKeOrxeHMX3E1WuC7OMvlMvBNyw4gc1hA86p5LS1Z5V8xuwyNnvVGft3iqUmk/mIwLxaUiM+lMv3VnYbukrFmkaM0Te/nr36Y8dKWV6J33TmkTBlRSYrc1+4ct3tcIvEzOf/vug3wZba74="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=ucsc_genomes_downloader --cov-report xml:coverage.xml 
- coverage combine
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email: false
